# Generated by Django 5.2.3 on 2025-06-17 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Filetype",
                    models.CharField(
                        choices=[
                            ("image", "image"),
                            ("videos", "videos"),
                            ("files", "files"),
                            ("gif", "gif"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("File", models.FileField(upload_to="uploads/")),
                (
                    "User_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
