# Generated by Django 5.2.3 on 2025-07-07 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="Uploaded_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
