# Generated by Django 5.2.3 on 2025-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_dashboard_uploaded_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
