# Generated by Django 5.2.3 on 2025-07-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_dashboard_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=100)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="File",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="Filetype",
            field=models.CharField(
                choices=[
                    ("image", "image"),
                    ("videos", "videos"),
                    ("files", "files"),
                    ("gif", "gif"),
                    ("link", "link"),
                ],
                max_length=100,
            ),
        ),
    ]
